name: "[DEV]"

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "[DEV] SSH Deploy"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/zuvy-eval-server
            git fetch origin
            git checkout dev
            git pull origin dev
            docker stop zuvy-eval-server
            docker rm zuvy-eval-server
            docker compose up -d --build
