name: deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_DEP }}
          username: ec2-user
          key: ${{ secrets.EVAL_DEP }}
          script: |
            cd /app
            git pull origin main
            docker stop zuvy-eval-server
            docker rm zuvy-eval-server
            docker compose up -d --build
